import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
// import { VisaIcon } from "../components/visa";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					SVG <a href="https://google.com">Icons</a> Credit Card
				</h1>
				<div className={styles.grid}>{/* <VisaIcon /> */}</div>
			</main>
		</div>
	);
}
